# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: admin@example.com
  admin_password: password
  domain_name: example.com
  secret_key_base: cc2b1b64aa8b184aa1bcd74fe38bc586205ddf911f3b6924793d9dd256a6ca94ca7fc71205db1518df963bea6e1221d6ea66d3b4b9afa1e5f7c178360f9ef392

test:
  domain_name: example.com 
  secret_key_base: 37f6874564955afaa5ad819e7ed4427ca04442d8213b7ebc32980160fae2ea817cf1fea5403eeca950919db4bd8c10339d59e2b87b1b02bd4104c65cebd0a3bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
